export enum EmailType {
  AccountVerification = 'account_verification',
  PasswordReset = 'password_reset',
  Welcome = 'welcome',
  BetWon = 'bet_won',
  BetLoss = 'bet_loss',
  BetWonGoldCoin = 'bet_won_gold_coin',
  CoinPurchase = 'coin_purchase',
  BettingStreamSummary = 'betting_stream_summary',
  ApplicationApproved = 'application_approved',
  ApplicationRejected = 'application_rejected',
  InboxMessage = 'inbox_message',
  ProSubscriptionActivated = 'pro_subscription_activated',
  ProSubscriptionCancelled = 'pro_subscription_cancelled',
  ConciergeAssigned = 'concierge_assigned',
  AuctionOutbid = 'auction_outbid',
  AuctionClosingSoon = 'auction_closing_soon',
  AuctionWon = 'auction_won',
  AuctionLost = 'auction_lost',
}
