export enum LiveFeedType {
    BET_ROUND_LOCKED = "BET_ROUND_LOCKED",
    BET_ROUND_CLOSED = "BET_ROUND_CLOSED",
    BET_ROUND_OPEN = "BET_ROUND_OPEN",
    RANK_UP = "BET_ROUND_LOCKED",
    BET_PLACED = "BET_PLACED",
}
