export enum SocketEventName {
  RefetchEvent = 'refetchEvent',
  NewMessage = 'newMessage',
  SendChatMessage = 'sendChatMessage',
  MessageSent = 'messageSent',
  JoinedStream = 'joinedStream',
  ViewerCountUpdated = 'viewerCountUpdated',
  ScheduledStreamUpdatedToLive = 'scheduledStreamUpdatedToLive',
  RoundUpdated = 'roundUpdated',
  StreamEnded = 'streamEnded',
  ChatMessage = 'chatMessage',
  LeaveStream = 'leaveStream',
  JoinStream = 'joinStream',
  JoinStreamBet = 'joinStreamBet',
  JoinedStreamBet = 'joinedStreamBet',
  LeaveStreamBet = 'leaveStreamBet',
  PlaceBet = 'placeBet',
  BetPlaced = 'betPlaced',
  BettingUpdate = 'bettingUpdate', // Round-level betting aggregates (roundId)
  VariableBettingUpdate = 'variableBettingUpdate', // Variable-level betting data (bettingVariableId)
  Error = 'error',
  PotentialAmountUpdate = 'potentialAmountUpdate',
  BotMessage = 'botMessage',
  CancelBet = 'cancelBet',
  EditBet = 'editBet',
  BetEdited = 'betEdited',
  WinnerDeclared = 'winnerDeclared',
  BetOpened = 'betOpened',
  BettingLocked = 'bettingLocked',
  BetCancelledByAdmin = 'betCancelledByAdmin',
  PurchaseSettled = 'purchaseSettled',
  StreamListUpdated = 'streamListUpdated',
  WithdrawSuccess = 'withdrawSuccess',
  WithdrawFailed = 'withdrawFailed',
}

export enum ChatType {
  System = 'System',
  User = 'User',
  Anonymous = 'Anonymous',
  StreambetBot = 'StreambetBot',
}
